/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ApiLibraryRouteImport } from './routes/api/library'
import { Route as GameCatalogIdRouteImport } from './routes/game.$catalogId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCatalogFeaturedRouteImport } from './routes/api/catalog.featured'
import { Route as ApiCatalogGameRouteImport } from './routes/api/catalog.game'
import { Route as ApiCatalogSearchRouteImport } from './routes/api/catalog.search'
import { Route as ApiLibraryIdRouteImport } from './routes/api/library.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryRoute = ApiLibraryRouteImport.update({
  id: '/api/library',
  path: '/api/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCatalogIdRoute = GameCatalogIdRouteImport.update({
  id: '/game/$catalogId',
  path: '/game/$catalogId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogFeaturedRoute = ApiCatalogFeaturedRouteImport.update({
  id: '/api/catalog/featured',
  path: '/api/catalog/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogGameRoute = ApiCatalogGameRouteImport.update({
  id: '/api/catalog/game',
  path: '/api/catalog/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogSearchRoute = ApiCatalogSearchRouteImport.update({
  id: '/api/catalog/search',
  path: '/api/catalog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryIdRoute = ApiLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/api/library': typeof ApiLibraryRouteWithChildren
  '/game/$catalogId': typeof GameCatalogIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/featured': typeof ApiCatalogFeaturedRoute
  '/api/catalog/game': typeof ApiCatalogGameRoute
  '/api/catalog/search': typeof ApiCatalogSearchRoute
  '/api/library/$id': typeof ApiLibraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/api/library': typeof ApiLibraryRouteWithChildren
  '/game/$catalogId': typeof GameCatalogIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/featured': typeof ApiCatalogFeaturedRoute
  '/api/catalog/game': typeof ApiCatalogGameRoute
  '/api/catalog/search': typeof ApiCatalogSearchRoute
  '/api/library/$id': typeof ApiLibraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/api/library': typeof ApiLibraryRouteWithChildren
  '/game/$catalogId': typeof GameCatalogIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/featured': typeof ApiCatalogFeaturedRoute
  '/api/catalog/game': typeof ApiCatalogGameRoute
  '/api/catalog/search': typeof ApiCatalogSearchRoute
  '/api/library/$id': typeof ApiLibraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/library'
    | '/login'
    | '/search'
    | '/stats'
    | '/api/library'
    | '/game/$catalogId'
    | '/api/auth/$'
    | '/api/catalog/featured'
    | '/api/catalog/game'
    | '/api/catalog/search'
    | '/api/library/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/library'
    | '/login'
    | '/search'
    | '/stats'
    | '/api/library'
    | '/game/$catalogId'
    | '/api/auth/$'
    | '/api/catalog/featured'
    | '/api/catalog/game'
    | '/api/catalog/search'
    | '/api/library/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/library'
    | '/login'
    | '/search'
    | '/stats'
    | '/api/library'
    | '/game/$catalogId'
    | '/api/auth/$'
    | '/api/catalog/featured'
    | '/api/catalog/game'
    | '/api/catalog/search'
    | '/api/library/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  ApiLibraryRoute: typeof ApiLibraryRouteWithChildren
  GameCatalogIdRoute: typeof GameCatalogIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCatalogFeaturedRoute: typeof ApiCatalogFeaturedRoute
  ApiCatalogGameRoute: typeof ApiCatalogGameRoute
  ApiCatalogSearchRoute: typeof ApiCatalogSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library': {
      id: '/api/library'
      path: '/api/library'
      fullPath: '/api/library'
      preLoaderRoute: typeof ApiLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$catalogId': {
      id: '/game/$catalogId'
      path: '/game/$catalogId'
      fullPath: '/game/$catalogId'
      preLoaderRoute: typeof GameCatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/featured': {
      id: '/api/catalog/featured'
      path: '/api/catalog/featured'
      fullPath: '/api/catalog/featured'
      preLoaderRoute: typeof ApiCatalogFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/game': {
      id: '/api/catalog/game'
      path: '/api/catalog/game'
      fullPath: '/api/catalog/game'
      preLoaderRoute: typeof ApiCatalogGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/search': {
      id: '/api/catalog/search'
      path: '/api/catalog/search'
      fullPath: '/api/catalog/search'
      preLoaderRoute: typeof ApiCatalogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/$id': {
      id: '/api/library/$id'
      path: '/$id'
      fullPath: '/api/library/$id'
      preLoaderRoute: typeof ApiLibraryIdRouteImport
      parentRoute: typeof ApiLibraryRoute
    }
  }
}

interface ApiLibraryRouteChildren {
  ApiLibraryIdRoute: typeof ApiLibraryIdRoute
}

const ApiLibraryRouteChildren: ApiLibraryRouteChildren = {
  ApiLibraryIdRoute: ApiLibraryIdRoute,
}

const ApiLibraryRouteWithChildren = ApiLibraryRoute._addFileChildren(
  ApiLibraryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  ApiLibraryRoute: ApiLibraryRouteWithChildren,
  GameCatalogIdRoute: GameCatalogIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCatalogFeaturedRoute: ApiCatalogFeaturedRoute,
  ApiCatalogGameRoute: ApiCatalogGameRoute,
  ApiCatalogSearchRoute: ApiCatalogSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
